### ISSUE TITLE
Краш при решении теста.

### ISSUE THREAD

**Issue by mishailovic** [superdima05/mesh#23]
`https://uchebnik.mos.ru/exam/test/view_test/309717/`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hotaru/mesh/mesh.py", line 232, in get_answers
    group_elements += generate_string(answer_entry) + ",\n\t"
  File "/home/hotaru/mesh/mesh.py", line 150, in generate_string
    option_text = option ["content"]
KeyError: 'content'
```

**Comment by superdima05** [comment]
[не будет решаться](https://github.com/superdima05/mesh/issues/15)
